/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'stefan' at '12/20/15 3:24 PM' with Gradle 2.6
 *
 * @author stefan, @date 12/20/15 3:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
